### ISSUE TITLE
You are trying to sign in from a browser or app that doesn't allow us to keep your account secure

### ISSUE THREAD

**Issue by siir4ever** [muraenateam/muraena#16] opened 2019-08-28 18:01 UTC
Hello , who got this error while testing google
Who got this error while testing google 

You are trying to sign in from a browser or app that doesn't allow us to keep your account secure.
Try using a different browser.
Thanks!

**Comment by expFakeMaker** [comment] 2019-09-03 08:39
A similar problem! I get the same message.
I understand this is Google’s new security system? I may be mistake.

**Comment by siir4ever** [comment] 2019-09-03 15:39
i think its an update

**Comment by robertsupport** [comment] 2019-09-03 20:00
I have the same error. And so in all browsers.
And 3 friends who are testing this problem. We do not know what to do.
Moreover, the same problem is observed in modlishka

**Comment by ohpe** [comment] 2019-09-03 20:19
I cannot replicate. It works ok to me. Please provide more details to support this issue or I'll close it.

**Comment by siir4ever** [comment] 2019-09-05 13:28
@ohpe when was the last time you tested it

**Comment by ohpe** [comment] 2019-09-06 15:28
When I wrote the comment. Add more details, no friend's feedback. What's the config?

**Comment by siir4ever** [comment] 2019-09-06 19:55
muraenas json config ; do you have other config ? , do you have any jabber icq for contact

**Closed** 2019-09-21 15:02 UTC

**Comment by acafeva** [comment] 2019-10-01 06:18
Iam having the same issue on multiple accounts, but it does not seems to happen on fresh created accounts. Try for example academyfeeva(at)gmail.com with any (wrong) password and default google config file. For account that does not suffer from this issue, Google respondes with message "..wrong password.." but for some accounts you get "you are trying to sing from a browser...". You dont even get to 2FA phase. I have read that some users have this problem with Brave browser even while signin to original google page.

**Comment by siir4ever** [comment] 2019-10-01 12:32
old accounts work , new ones , no

**Comment by acafeva** [comment] 2019-10-01 14:19
For me the opposite, fresh accounts work but the old ones do not..

**Comment by Equidamoid** [comment] 2019-12-11 22:02
For those frustrated because the problem is there, but the bug is closed, a workaround:
```
:set content.headers.user_agent "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:64.0) Gecko/20100101 Firefox/64.0"
```

**Comment by The-Compiler** [comment] 2019-12-12 08:17
@Equidamoid This isn't the qutebrowser repository :wink:

**Comment by Equidamoid** [comment] 2019-12-16 18:19
@The-Compiler 
oh man, sorry, that was too late in the evening apparently =)
